    image: node:latest

    stages:
      - build
      - test
      - containerize

    cache:
      paths:
        - node_modules/

    install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

    testing_testing:
      stage: test
      script: npm test

    build_container:
      stage: containerize
      script:
        - docker info
        - docker build -t myimage .
